config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users
   devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
  resources :leave_applications
  resources :leave_dates
  resources :leave_types
  get 'leave_analysis', to: 'leave_analysis#index',as: :leave_analysis

  namespace :api do
      resources :leave_dates, only: [:index]
  end

  namespace :employee do
      get ":user_id/dashboard", to: "dashboard#index",as: :dashboard
      get ":user_id/leave_applications",to: "leave_applications#index",as: :leave_applications
      get ":user_id/leave_application/new",to: "leave_applications#new",as: :new_leave_application
      get ":user_id/leave_analysis",to: "leave_analysis#index",as: :leave_analysis
  end

end

app/models/leave_application.rb
class LeaveApplication < ActiveRecord::Base
  belongs_to :user
  has_many :leave_dates, dependent: :destroy
  accepts_nested_attributes_for :leave_dates, allow_destroy: true
  validates :application_date, presence: true

  private

end

app/controllers/employee/base_controller.rb
class Employee::BaseController < ApplicationController
	layout "employee"
	before_filter :authenticate_and_get_user


	private 


	def authenticate_and_get_user
		@user = User.find(params[:user_id])
		unless @user === current_user
			raise Pundit::NotAuthorizedError
		end
	end

end

app/controllers/employee/dashboard_controller.rb
class Employee::DashboardController < Employee::BaseController

	def index
	end
end

app/controllers/employee/leave_analysis_controller.rb
class Employee::LeaveAnalysisController < Employee::BaseController

	def index
		@chart_element = "user-leave-count-chart"
	end

end

app/controllers/employee/leave_applications_controller.rb
class Employee::LeaveApplicationsController < Employee::BaseController
  
  def index
  	@leave_applications = @user.leave_applications.page(params[:page])
  end

  def new
  	@leave_application = @user.leave_applications.build
  end
end

app/controllers/leave_applications_controller.rb
class LeaveApplicationsController < ApplicationController
  before_action :set_leave_application, only: [:show, :edit, :update, :destroy]

  # GET /leave_applications
  # GET /leave_applications.json
  def index
    @leave_applications = LeaveApplication.page(params[:page])
  end

  # GET /leave_applications/1
  # GET /leave_applications/1.json
  def show
    respond_to do|format|
      format.html
      format.pdf do
        leave_dates = @leave_application.leave_dates.order(:date).eager_load(:leave_period)
        pdf = LeaveApplicationPdf.new(@leave_application,leave_dates,@leave_application.user)
        send_data pdf.render, filename: "#{@leave_application.application_date}_#{@leave_application.user.name}.pdf",
                                        type: "application/pdf",
                                        disposition: "inline"
      end
    end
  end

  # GET /leave_applications/new
  def new
    @leave_application = LeaveApplication.new
  end

  # GET /leave_applications/1/edit
  def edit
  end

  # POST /leave_applications
  # POST /leave_applications.json
  def create
    @leave_application = LeaveApplication.new(leave_application_params)
    respond_to do |format|
      if @leave_application.save!
        format.html { redirect_to @leave_application, notice: 'Leave application was successfully created.' }
        format.json { render :show, status: :created, location: @leave_application }
      else
        format.html { render :new }
        format.json { render json: @leave_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leave_applications/1
  # PATCH/PUT /leave_applications/1.json
  def update
    respond_to do |format|
      if @leave_application.update(leave_application_params)
        format.html { redirect_to @leave_application, notice: 'Leave application was successfully updated.' }
        format.json { render :show, status: :ok, location: @leave_application }
      else
        format.html { render :edit }
        format.json { render json: @leave_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leave_applications/1
  # DELETE /leave_applications/1.json
  def destroy
    @leave_application.destroy
    respond_to do |format|
      format.html { redirect_to leave_applications_url, notice: 'Leave application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leave_application
      @leave_application = LeaveApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leave_application_params
      params.require(:leave_application).permit(:application_date, :reason,:user_id, leave_dates_attributes: [:id,:date,:leave_period_id,:_destroy])
    end
end

app/helpers/employee/dashboard_helper.rb
module Employee::DashboardHelper
end

app/helpers/leave_applications_helper.rb
module LeaveApplicationsHelper
end

app/views/employee/leave_applications/_leave_date_fields.html.erb
<%= render partial: "leave_applications/leave_date_fields",locals: {f: f}%>

app/views/employee/leave_applications/index.html.erb
<h1 class="text-center">Listing leave_applications</h1>
<div class="row">
  <div class="large-4 large-offset-3 columns">
    <div class="user-show-container panel callout radius">
      <table>
  <thead>
    <tr>
      <th>Application date</th>
      <th>User</th>
      <th>Leave Dates</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leave_applications.each do |leave_application| %>
      <tr>
        <td><%= leave_application.application_date %></td>
        <td><%= link_to leave_application.user.name, user_path(leave_application.user)%></td>
        <td>
            <% leave_application.leave_dates.each do|ld| %>
                <%= ld.date %> ,
            <% end %>
        </td>
        <td><%= link_to 'Show', leave_application %></td>
        <td><%= link_to 'Edit', edit_leave_application_path(leave_application) %></td>
        <td><%= link_to 'Destroy', leave_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @leave_applications %>
<br>

<%= link_to 'New Leave application', new_leave_application_path,class: 'button large success radius' %>
    </div>
  </div>
</div>

app/views/employee/leave_applications/new.html.erb
<div class="user-show-container panel callout radius">
<%= nested_form_for(@leave_application) do |f| %>
  <% if @leave_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leave_application.errors.count, "error") %> prohibited this leave_application from being saved:</h2>

      <ul>
      <% @leave_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :application_date %><br>
    <%= f.text_field :application_date ,class: "dpk"%>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason,rows: 4%>
  </div>
  <div class="leave_dates panel callout radius">
    <div class="fields_count"></div>
    <%= f.fields_for :leave_dates %>
    <p><%= f.link_to_add "Add a date",:leave_dates,class: "button tiny primary" %></p>
  </div>
  <div class="actions row">
    <div class="large-4 large-offset-4 columns">
      <%= f.submit 'Save',class: 'button tiny primary'%>
    </div>
  </div>
<% end %>
</div>