config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users
   devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
  resources :leave_applications
  resources :leave_dates
  resources :leave_types
  get 'leave_analysis', to: 'leave_analysis#index',as: :leave_analysis

  namespace :api do
      resources :leave_dates, only: [:index]
  end

  namespace :employee do
      get ":user_id/dashboard", to: "dashboard#index",as: :dashboard
      get ":user_id/leave_applications",to: "leave_applications#index",as: :leave_applications
      get ":user_id/leave_application/new",to: "leave_applications#new",as: :new_leave_application
      get ":user_id/leave_analysis",to: "leave_analysis#index",as: :leave_analysis
  end

end

app/views/layouts/shared/_dashboard_nav.html.erb
<section class="top-bar-section">
  <!-- Left Nav Section -->
  <ul class="left">
    <li class="divider"></li>
    <li class="<%= is_active?(employee_leave_analysis_path) %>"><%= link_to "My Leave Status", employee_leave_analysis_path %></li>
    <li class="divider"></li>
    <li class="<%= is_active?(employee_leave_applications_path) %>"><%= link_to "My Leave Applications", employee_leave_applications_path %></li>
    <li class="divider"></li>
    <li class="<%= is_active?(employee_new_leave_application_path) %>"><%= link_to "New Leave Application", employee_new_leave_application_path %></li>
    <li class="divider"></li>
    <li class="<%= is_active?(employee_dashboard_path) %>"><%= link_to "Profile", employee_dashboard_path %></li>
    <li class="divider"></li>
  </ul>

  <!-- Right Nav Section -->
  <ul class="right">
  <li class="has-form">
      <form>
        <div class="row collapse">
          <div class="small-8 columns">
            <input type="text">
          </div>
          <div class="small-4 columns">
            <a href="#" class="alert button">Search</a>
          </div>
        </div>
      </form>
    </li>
    <li class="divider show-for-small"></li>
    <li class="has-form">
    <% unless current_user.nil? %>
      <%= link_to "Log out", destroy_session_path(current_user),method: :delete %>
    <%else %>
      <%= link_to "Log in", new_user_session_path() %>
    <% end %>
    </li>
  </ul>
</section>

app/views/layouts/shared/_flash_alert.html.erb
 <div id="flash" data-alert class="alert-box warning text-center">
     <%= h flash[:alert] %>
 <a href="#" class="close">&times;</a>
</div> 

app/views/layouts/shared/_flash_error.html.erb
<div id="flash" data-alert class="alert-box alert text-center">
      <%= h flash[:error] %>
  <a href="#" class="close">&times;</a>
</div>  

app/views/layouts/shared/_flash_notice.html.erb
 <div id="flash" data-alert class="alert-box success text-center">
     <%= h flash[:notice] %>
 <a href="#" class="close">&times;</a>
</div>   

app/views/layouts/shared/_primary_nav.html.erb
<section class="top-bar-section">
  <!-- Left Nav Section -->
  <ul class="left">
    <li class="divider"></li>
    <li class="<%= is_active?(leave_analysis_path) %>"><%= link_to "Leave Analysis", leave_analysis_path %></li>
    <li class="divider"></li>
    <li class="<%= is_active?(leave_applications_path) %>"><%= link_to "Leave Applications", leave_applications_path %></li>
    <li class="divider"></li>
    <li class="<%= is_active?(teams_path) %>"><%= link_to "Teams", teams_path %></li>
    <li class="divider"></li>
    <li class="<%= is_active?(users_path) %>"><%= link_to "Employees", users_path %></li>
    <li class="<%= is_active?(leave_types_path) %>"><%= link_to "Leave Types", leave_types_path %></li>
    <li class="divider"></li>
  </ul>

  <!-- Right Nav Section -->
  <ul class="right">
  <li class="has-form">
      <form>
        <div class="row collapse">
          <div class="small-8 columns">
            <input type="text">
          </div>
          <div class="small-4 columns">
            <a href="#" class="alert button">Search</a>
          </div>
        </div>
      </form>
    </li>
    <li class="divider show-for-small"></li>
    <li class="has-form">
    <% unless current_user.nil? %>
      <%= link_to "Log out", destroy_session_path(current_user),method: :delete %>
    <%else %>
      <%= link_to "Log in", new_user_session_path() %>
    <% end %>
    </li>
  </ul>
</section>