config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users
   devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
  resources :leave_applications
  resources :leave_dates
  resources :leave_types
  get 'leave_analysis', to: 'leave_analysis#index',as: :leave_analysis

  namespace :api do
      resources :leave_dates, only: [:index]
  end

  namespace :employee do
      get ":user_id/dashboard", to: "dashboard#index",as: :dashboard
      get ":user_id/leave_applications",to: "leave_applications#index",as: :leave_applications
      get ":user_id/leave_application/new",to: "leave_applications#new",as: :new_leave_application
      get ":user_id/leave_analysis",to: "leave_analysis#index",as: :leave_analysis
  end

end

app/controllers/leave_types_controller.rb
class LeaveTypesController < ApplicationController
	before_filter :find_leave_type, only: [:show,:edit,:update,:destroy]

	def index
		@leave_types = LeaveType.all
	end

	def new
		@leave_type = LeaveType.new
	end

	def create
		@leave_type = LeaveType.new(leave_type_params)
		respond_to do |format|
		  if @leave_type.save!
		    format.html { redirect_to @leave_type, notice: 'Leave Type was successfully created.' }
		    format.json { render :show, status: :created, location: @leave_type }
		  else
		    format.html { render :new }
		    format.json { render json: @leave_type.errors, status: :unprocessable_entity }
		  end
		end
	end

	def show

	end

	def edit

	end

	def update
		respond_to do |format|
		  if @leave_type.update(leave_type_params)
		    format.html { redirect_to @leave_type, notice: 'Leave Type was successfully updated.' }
		    format.json { render :show, status: :ok, location: @leave_type }
		  else
		    format.html { render :edit }
		    format.json { render json: @leave_type.errors, status: :unprocessable_entity }
		  end
		end
	end

	def destroy
		@leave_type.destroy
		respond_to do |format|
		  format.html { redirect_to leave_types_url, notice: 'Leave application was successfully destroyed.' }
		  format.json { head :no_content }
		end
	end

	private

	def find_leave_type
		@leave_type = LeaveType.find(params[:id])
	end

	def leave_type_params
		params.require(:leave_type).permit(:name)
	end
end

app/helpers/leave_types_helper.rb
module LeaveTypesHelper
end

app/views/leave_types/_form.html.erb
<%= form_for(@leave_type) do |f| %>
  <% if @leave_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leave_type.errors.count, "error") %> prohibited this leave_type from being saved:</h2>

      <ul>
      <% @leave_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leave_types/edit.html.erb
<h1>Editing leave_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @leave_type %> |
<%= link_to 'Back', leave_types_path %>

app/views/leave_types/index.html.erb
<h1>Listing leave_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leave_types.each do |leave_type| %>
      <tr>
        <td><%= leave_type.name %></td>
        <td><%= link_to 'Show', leave_type %></td>
        <td><%= link_to 'Edit', edit_leave_type_path(leave_type) %></td>
        <td><%= link_to 'Destroy', leave_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New leave_type', new_leave_type_path %>

app/views/leave_types/new.html.erb
<h1>New leave_type</h1>

<%= render 'form' %>

<%= link_to 'Back', leave_types_path %>

app/views/leave_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @leave_type.name %>
</p>

<%= link_to 'Edit', edit_leave_type_path(@leave_type) %> |
<%= link_to 'Back', leave_types_path %>